name: Draft PDF

on:
  push:
    paths:
      - "paper/**"
      - ".github/workflows/draft-pdf.yml"

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Build JOSS draft PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v0.1.4
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper/paper.pdf
