name: Draft PDF

on:
  push:
    paths:
      - "paper/**"
      - ".github/workflows/draft-pdf.yml"

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Build JOSS draft PDF
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build draft PDF
        # use released version instead of master branch
        uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss
          # path relative to repo root: paper/paper.md
          paper-path: paper/paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          # Pandoc will write the compiled PDF next to paper.md by default
          path: paper/paper.pdf
